name = "flow"
entrypoint = "src/index.js"
extensions = [
  "js"
]
packages = []
setup = [
  "npm install -g flow-language-server-amasad flow-bin"
]

[run]
command = [
  "yarn",
  "start"
]

[languageServer]
command = [
  "flow-language-server",
  "--stdio"
]
