name = "clojure"
entrypoint = "main.clj"
extensions = [
  "clj",
  "cljc",
  "cljs",
  "edn"
]
packages = [
  "openjdk-11-jre-headless"
]
setup = [
  "wget https://download.clojure.org/install/linux-install-1.10.1.536.sh",
  "chmod +x linux-install-1.10.1.536.sh",
  "./linux-install-1.10.1.536.sh",
  "rm linux-install-1.10.1.536.sh",

  # Trigger downloading of Clojure JARs now to avoid downloading them at runtime.
  # (https://clojure.org/reference/deps_and_cli#_command_line_tools)
  """clojure \
    -Sdeps '{:deps {org.clojure/tools.namespace {:mvn/version "1.0.0"}} :paths ["src" "."] :mvn/local-repo "/home/runner/.m2/repository"}' \
    -Sforce \
    -Sverbose \
    --eval ''""",

  "/usr/bin/build-prybar-lang.sh clojure"
]
versionCommand = [
  "clj",
  "-Sdeps",
  """{:deps {org.clojure/tools.namespace {:mvn/version "1.0.0"}} :paths ["src" "."] :mvn/local-repo "/home/runner/.m2/repository"}""",
  "--eval",
  "(clojure-version)"
]

[run]
command = [
  "clj",
  "-Sdeps",
  """{:deps {org.clojure/tools.namespace {:mvn/version "1.0.0"}} :paths ["src" "."] :mvn/local-repo "/home/runner/.m2/repository"}""",
  "main.clj"
]

[tests]

  [tests.hello]
  code = "(println \"hello\")"
  output = "hello\n"
