name = "obratnaya"
entrypoint = "main.oba"
extensions = [
  "stk"
]
aptKeys = ["3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF"]
aptRepos = [
  "deb https://download.mono-project.com/repo/ubuntu stable-bionic main"
]
packages = [
  "mono-complete"
]
setup = [
  "cd /tmp",
  "wget https://repl.it/@obratnaya/Obratnaya.zip",
  "unzip Obratnaya.zip \"obrya.exe\"",
  "mv obrya.exe /usr/bin/obrya.exe",
  "rm -rf Obratnaya.zip"
]

[run]
command = [
  "mono",
  "/usr/bin/obrya.exe",
  "main.oba"
]

[tests]

  [tests.hello]
  code = ".data:\n    .text hello\n.main:\n    mov 0,@\n    msg @\n    cr\n    lf\n    ret"
  output = "hello\r\n"
