name = "ocaml"
entrypoint = "main.ml"
extensions = [
  "ml"
]

aptKeys = []
aptRepos = [
  "ppa:avsm/ppa"
]


packages = [
  "m4",
  "ocaml",
  "opam"
]

setup = [
  "opam init -c ocaml-system -n --disable-sandboxing",
  "/usr/bin/build-prybar-lang.sh ocaml"
]

[compile]
command = [
  "ocamlc",
  "-o",
  "main"
]

[run]
command = [
  "./main"
]

[tests]

  [tests.hello]
  code = """print_string "hello world!\n";;"""
  output = "hello world!\n"
