name = "python"
entrypoint = "main.py"
extensions = [
  "py"
]
packages = [
  "python-pip",
  "python-wheel",
  "python-dev",
  "libtk8.6",
  "python-dev",
  "libevent-dev",
  "gcc",
  "python-tk",
  "tk-dev"
]
setup = [
  "wget https://storage.googleapis.com/container-bins/stderred_1.0_amd64.deb && dpkg -i stderred_1.0_amd64.deb && rm stderred_1.0_amd64.deb",
  "pip2 install -U setuptools",
  "pip2 install -U configparser",
  "pip2 install --no-cache-dir pipreqs-amasad==0.4.10 jedi==0.12.1 pyflakes==2.0.0 rope==0.11.0 yapf==0.25.0 mccabe==0.6.1 nltk numpy scipy requests matplotlib bpython ptpython",
]

[run]
command = [
  "python2",
  "-B",
  "main.py"
]

[tests]

  [tests.hello]
  code = "print \"hello\""
  output = "hello\n"

[languageServer]
command = [
  "pyls",
  "-v"
]
