name = "reactjs"
entrypoint = "src/index.js"
extensions = [
  "js"
]
packages = []
setup = [
  "rm -f /home/runner/.profile /home/runner/.bashrc /home/runner/.bash_logout && npx create-react-app /home/runner && yarn && rm README.md && chown runner:runner -R /home/runner && yarn global add prettier@1.13.4"
]

[run]
command = [
  "yarn",
  "start"
]
