name = "rust"
entrypoint = "main.rs"
extensions = [
  "rs"
]
packages = [
  "rust-gdb"
]
setup = [
  "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | CARGO_HOME=/opt/rust RUSTUP_HOME=/opt/rust sh -s -- -y --default-toolchain 1.49.0 --component rust-src",
  "curl -L https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-linux -o /usr/local/bin/rust-analyzer",
  "chmod +x /usr/local/bin/rust-analyzer",
]

[compile]
command = [
  "rustc",
  "-o",
  "main"
]

[run]
command = [
  "./main"
]

[languageServer]
command = [
  "rust-analyzer"
]

[tests]

  [tests.hello]
  code = "fn main() {\n  println!(\"hello\");\n}"
  output = "hello\n"
