name = "scala"
entrypoint = "Main.scala"
extensions = [
  "scala"
]
packages = [
  "openjdk-11-jdk",
  "scala"
]
setup = [
]

[compile]
command = [
  "scalac"
]

[run]
command = [
  "scala",
  "Main"
]
pty = true

[tests]

  [tests.hello]
  code = "object Main { def main(args: Array[String]) { println(\"Hello, world!\") } }\n"
  output = "Hello, world!\n"

